version: "3"
 
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80
    environment:
      TZ: "Asia/Tokyo"
    depends_on:
      - db
 
  db:
    image: mysql:5
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3309:3306" # 3306ポートにするとローカルのMySQLと被るのでポートをずらす。
    environment:
      MYSQL_DATABASE: cakephp_db
      MYSQL_ROOT_PASSWORD: root_password
       
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
 
volumes:
  db-data:
    external: false